### ISSUE TITLE
Empty CMapStringToString object

### ISSUE THREAD

**Issue by CongweiWu** [mariusbancila/mfccollectionutilities#2]
I just attach the sample code to explain the issue I found.

-------------------------------------------------------------------------------
	CMapStringToString myMap;
	myMap.RemoveAll();
	int iCount1 = 0; 
	for (auto& each: myMap) {
		iCount1++;
	}

	int iCount2 = 0;
	for (POSITION pos = myMap.GetStartPosition(); pos != NULL; ) {
		iCount2++;
	}
----------------------------------------------------------------------------------

I assume the variables "iCount1" and "iCount2" in above code return  0, however iCount1 returns 1.  Am I missing something here?

**Comment by mariusbancila** [comment]
I can confirm, this is a bug.

**Comment by mariusbancila** [comment]
fixed

**Comment by CongweiWu** [comment]
Working now. Thanks.
